// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://tntmojiyzugsvimxcflp.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRudG1vaml5enVnc3ZpbXhjZmxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk2OTcyMDIsImV4cCI6MjA0NTI3MzIwMn0.hlL_Jxd0JuHByXzM6LVeZ44LMSf7gVGPOFYOZqJSmuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);